name: "PullRequest"

on:
  push:
  pull_request:

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 1
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@0.0.7
      - name: Build project
        run: cd software && ./gradlew assembleDebug
        env:
          VERSION: ${{ github.ref }}
      - name: Run tests
        run: cd software && ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: IOIO-Espresso-report
          path: applications/**/build/reports/androidTests/connected/
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: IOIO-logcat
          path: artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v2.1.4
        if: ${{ always() }}
        with:
          name: IOIO-Screenshots
          path: applications/screenshots/adb/
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 1
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@0.0.7
      - name: Code checks
        run: cd software && ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.0.1
        if: ${{ always() }}
        with:
          name: IOIO-Lint-report
          path: software/app/build/reports/lint-results.html
