name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Change directory
        run: cd software
      - uses: gradle/wrapper-validation-action@v1